# Generated by Django 4.0.5 on 2022-08-03 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lts', '0002_rename_name_servicerequest_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
